import tags from '$common/DisplayAnyContent/tagsMap';

export default [
	{ tag: tags.b, text: 'Earning up to 80% profit share commission' },
	{
		tag: tags.ul,
		text: [
			'Increase your profile status to raise your profit share commission from 50% to 80% as an IB!'
		]
	},
	{ tag: tags.b, text: 'Attract new clients and receive additional bonuses!' },
	{ tag: tags.ul, text: ['The more clients with FTD you attract, the higher the bonus amount!'] },
	{ tag: tags.b, text: "Earn on your referrals' net turnover!" },
	{
		tag: tags.ul,
		text: [
			'Receive a commission from each bet your referral places. When the company profits, you also earn additional income from commission distribution.'
		]
	},
	{ tag: tags.h2, text: 'Exclusive Conditions For Pocket Option Partners' },
	{
		tag: tags.ul,
		text: [
			'<b>Profit distribution:</b> An extended profit distribution system with passive long-term income.',
			"<b>FTD Bonuses:</b> An additional bonus system with payouts for clients' initial deposits.",
			'<b>Weekly payouts:</b> The higher your profile status, the more frequent payouts you can receive.',
			'<b>Net turnover commission:</b> Receive commission for the trading volume generated by your referrals. The higher the volume, the greater your earnings.',
			'<b>Partner contests with free participation:</b> Earn extra commissions and win fantastic prizes for your performance.',
			'<b>Extensive promotional materials</b>',
			'<b>Postbacks for automation</b>',
			'<b>Round-the-clock support and assistance</b>',
			'<b>Sub-affiliate program</b>',
			'<b>Mobile apps and links</b>'
		]
	},
	{ tag: tags.h2, text: 'How To Become A&nbsp;Partner' },
	{
		tag: tags.ol_ul,
		text: [
			{
				li: '<b>Register a partner account</b>',
				list: ['Be productive and increase your profile status to raise your commission to 80%']
			},
			{
				li: '<b>Refer new clients</b>',
				list: ['The more active referrals you have, the higher your commission and bonus.']
			},
			{
				li: '<b>Clients start trading</b>',
				list: ['And generate trading volume on their Pocket Option accounts.']
			},
			{
				li: '<b>Earn a commission for each active referral</b>',
				list: ['Depending on the chosen partner campaign and partner status']
			}
		]
	},

	{ tag: tags.h2, text: 'Types Of Offers For Your Partner Campaigns' },
	{
		tag: tags.text,
		text: 'Split and merge your traffic streams to maximize your income from our affiliate program; you can choose any type of offer for your partner campaigns'
	},
	{ tag: tags.b, text: 'Revenue Sharing Offer' },
	{
		tag: tags.ul,
		text: [
			"You receive a commission from the Company's profits depending on the overall trading activity of your referrals."
		]
	},
	{ tag: tags.b, text: 'Deposit Split Offer' },
	{
		tag: tags.ul,
		text: ['You receive a commission based on the initial deposits made by your referrals.']
	},
	{ tag: tags.b, text: 'Volume Share Offer' },
	{
		tag: tags.ul,
		text: [
			"You receive a commission based on the overall trading volume of your referrals and a commission from the Company's profits based on the overall trading activity of your referrals."
		]
	},
	{ tag: tags.b, text: 'Turnover Distribution Offer' },
	{
		tag: tags.ul,
		text: ['You receive a commission based on the total trading volume of your referrals.']
	},
	{ tag: tags.b, text: 'CPA Offer' },
	{
		tag: tags.ul,
		text: [
			'You receive a one-time commission for attracting an active customer based on GEO and FTD quantity.'
		]
	},
	{ tag: tags.b, text: 'Sub-affiliate program' },

	{ tag: tags.h2, text: 'Profile Levels' },
	{ tag: tags.img, id: 1, thumb: [760, 435], full: [1680, 961] },
	{ tag: tags.img, id: 2, thumb: [760, 438], full: [1680, 969] },
	{ tag: tags.img, id: 3, thumb: [760, 438], full: [1680, 968] },
	{ tag: tags.img, id: 4, thumb: [760, 440], full: [1680, 972] }
];
