export default [
	{ method: 'Visa, Mastercard (3DS2)', dep: '$5', time: '~1 min.' },
	{ method: 'Perfect Money', dep: '$5', time: '~1 min.' },
	{ method: 'Advcash', dep: '$5', time: 'Instant' },
	{ method: 'WebMoney', dep: '$5', time: 'Instant' },
	{ method: 'Payeer', dep: '$5', time: '1 min.' },
	{ method: 'Jeton', dep: '$5', time: 'Instant' },
	{ method: 'Bitcoin (BTC)', dep: '$50', time: '~28 min.' },
	{ method: 'Tether (USDT)', dep: '$10', time: '~10 min.' },
	{ method: 'Binance Pay', dep: '$5', time: '~1 min.' },
	{ method: 'Tether TRC-20', dep: '$10', time: '~11 min.' },
	{ method: 'Litecoin (LTC)', dep: '$50', time: '~12 min.' },
	{ method: 'Ethereum (ETH) ERC-20', dep: '$20', time: '~42 min.' },
	{ method: 'Bitcoin Cash (BCH)', dep: '$10', time: '3-5 min.' },
	{ method: 'USD Coin (USDC) ERC-20', dep: '$20', time: '~31 min.' },
	{ method: 'Stellar (XLM)', dep: '$10', time: '~1 hour' },
	{ method: 'Tether ERC-20', dep: '$20', time: '~21 min.' },
	{ method: 'USD Coin (USDC)', dep: '$5', time: '~12 min.' },
	{ method: 'Tron (TRX)', dep: '$25', time: '~47 min.' },
	{ method: 'Ripple (XRP)', dep: '$30', time: '~56 min.' },
	{ method: 'Ethereum Classic (ETC)', dep: '$10', time: '~1 hour' },
	{ method: 'USD Coin (USDC) TRC-20', dep: '$10', time: '~21 min.' },
	{ method: 'Tether Polygon (USDT)', dep: '$10', time: '~22 min.' },
	{ method: 'Shiba Inu (SHIB)', dep: '$40', time: '~23 min.' },
	{ method: 'Dogecoin (DOGE)', dep: '$50', time: '~19 min.' },
	{ method: 'Polygon (MATIC)', dep: '$50', time: '3-5 min.' },
	{ method: 'Chainlink (LINK)', dep: '$50', time: '3-5 min.' },
	{ method: 'Cardano (ADA)', dep: '$50', time: '~29 min.' },
	{ method: 'Binance Coin (BNBBSC)', dep: '$100', time: '~1 hour' },
	{ method: 'Cosmos (ATOM)', dep: '$50', time: '3-5 min.' },
	{ method: 'Toncoin (TON)', dep: '$50', time: '3-5 min.' },
	{ method: 'Uniswap (UNI)', dep: '$50', time: '3-5 min.' },
	{ method: 'Algorand (ALGO)', dep: '$50', time: '~22 min.' },
	{ method: 'Polkadot (DOT)', dep: '$50', time: '~16 min.' },
	{ method: 'Cronos (CRO)', dep: '$50', time: '~17 min.' },
	{ method: 'Dai (DAI)', dep: '$50', time: '~2 hours' },
	{ method: 'Zcash (ZEC)', dep: '$110', time: '~7 min.' },
	{ method: 'ApeCoin (APE)', dep: '$50', time: '3-5 min.' },
	{ method: 'Avalanche (AVAX)', dep: '$50', time: '~22 min.' }
];
